use `college_app`;

DROP TABLE IF EXISTS `student`;
CREATE TABLE `student` (
	`id` VARCHAR(255) NOT NULL,
	`FIRST_NAME` VARCHAR(255) NULL DEFAULT NULL,
	`LAST_NAME` VARCHAR(255) NULL DEFAULT NULL,
	`CREATED_BY` VARCHAR(50) NOT NULL,
	`CREATED_ON` BIGINT(20) NOT NULL,
	`LAST_UPDATED_BY` VARCHAR(50) NULL DEFAULT NULL,
	`LAST_UPDATED_ON` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)ENGINE=InnoDB;


INSERT INTO `student` (`id`, `FIRST_NAME`, `LAST_NAME`, `CREATED_BY`, `CREATED_ON`, `LAST_UPDATED_BY`, `LAST_UPDATED_ON`) VALUES ('1', 'fstname', 'lstname', 'system', 1495109408649, 'system', 1495109408649);
